config/routes.rb
Rails.application.routes.draw do

  
   root to: 'ads#index'
   get '/ads/:id' => "ads#show" , :as => "ads_show"
   

   resources :ads
   

end

app/models/ad.rb
class Ad < ActiveRecord::Base
	validates_presence_of :name, :description, :price, :seller_id, :email, :img_url,length: {minimum: 3}
    validates_numericality_of :price, :seller_id

end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
#before_action :set_ad, only: [:show]
def new
@ad=Ad.new

end

def create
	 @ad=Ad.new(ad_params)
	 if @ad.save
	 redirect_to ad_path(@ad.id)
   else 
    render 'new'
   end  
end

def show 
 @ad = Ad.find(params[:id])
end

def index
    @ads = Ad.all
end

private
    def ad_params
       params.require(:ad).permit(:name, :description, :price, :seller_id, :email, :img_url)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ads/_form.html.erb
  <% if @ad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ad.errors.count, "error") %> prohibited this ad from being saved:</h2>

      <ul>
      <% @ad.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
<% end %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :Description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :Price %><br>
    <%= f.text_area :price %>
  </div>
  <div class="field">
    <%= f.label :Seller_id %><br>
    <%= f.text_field :seller_id %>
  </div>
  <div class="field">
    <%= f.label :Email %><br>
    <%= f.text_field :email %>
  </div>
  
  <div class="field">
    <%= f.label :Image %><br>
    <%= f.text_field :img_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

app/views/ads/index.html.erb
<html>
<head>
<title>All Ads</title>
</head>
<body>
<h1>All Ads</h1>
<ul>
<% for ad in @ads %>
<li><a href="/ads/<%= ad.id %>"><%= ad.name %></a></li>
<% end %>
</ul>
</body>
</html>

app/views/ads/new.html.erb
<h1><u>New Advertise</u></h1>
<%= form_for @ad , url: ads_path do |f| %>
<%= render :partial => 'form', locals: {:f => f} %>


<%= link_to 'Back', new_ad_path %>
<% end %>

app/views/ads/show.html.erb
<html>
<head>

<title><%= @ad.name %></title>
</head>
<body>
<p>
<b>Name:</b>
<%= @ad.name %>
</p>
<p>
<b>Description:</b>
<%= @ad.description %>
</p>
<p>
<b>Price:</b>
<%= @ad.price %>
</p>
<p>
<b>Seller Id:</b>
<%= @ad.seller_id %>
</p>
<p>
<b>Email:</b>
<%= @ad.email %>
</p>
<p>
<img src="<%= @ad.img_url %>"/>
</p>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mebay</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>